spring:
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 266057497231-lbkstjk1ka1joahd1t705mno75hgjout.apps.googleusercontent.com
            clientSecret: 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
            redirect-uri: "https://8081-idx-movie-project-1717140701197.cluster-bs35cdu5w5cuaxdfch3hqqt7zm.cloudworkstations.dev/login/oauth2/code/google"

server:
  port: 8081
# ...